### ISSUE TITLE
Unable to handle deleted or rejected attachments without Name tags

### ISSUE THREAD

**Issue by rickardl** [telia-oss/cloudconnect#1]
When the lambda encounters a deleted or rejected (manually) attachment, the tag has not yet been populated with the Name attribute, on processing the lambda encounters a null pointer exception and crashes.

See the following excerpt of the offending lines

```go
nameTag, _ := a.Tags["Name"]
if nameTag != allocation.Name {
  return TagAttachment, "name tag does not match allocation", nil
}
```

We do a direct reference to the value with key, instead of using the standardised method to make safe calls.

The below method adds a guard when fetching key values.

```go
if nameTag, ok := a.Tags["Name"]; ok {
  if nameTag != allocation.Name {
	  return TagAttachment, "name tag does not match allocation", nil
  }
}
```

I'll shortly add a PR that correctly handles this.

**Comment by itsdalmo** [comment]
Ah, sorry about that one! Great fix 👍
